name: mlflow-demo
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - pyspark
  - pip
  - pip:
    - databricks
    - koalas
    - mlflow
    - hyperopt
    - ipython
    - shap